version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 583323754395.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - docker build -t my-ecommerce-app .
      - docker tag my-ecommerce-app:latest 583323754395.dkr.ecr.eu-north-1.amazonaws.com/codebuild:latest

  post_build:
    commands:
      - docker push 583323754395.dkr.ecr.eu-north-1.amazonaws.com/codebuild:latest

      - echo "Starting ECS deployment..."

      - aws ecs update-service \
          --cluster codebuild-cluster \
          --service codebuildtask-service-8s1w4pea \
          --force-new-deployment

artifacts:
  files:
    - '**/*'
